# Log the results of DNS queries handled by dnsmasq.
log-queries

# Don't read /etc/resolv.conf.
no-resolv

# Don't write a PID file, since dnsmasq runs as the container's main process.
pid-file=

# Forward all queries to Docker's DNS server.
server=127.0.0.11
